---
title: "Work"
format:
  html:
    toc: true
    toc-depth: 2
---

## Quadeye  
**Quantitative Strategist Full-time (2023–2025)**

The two years at Quadeye have flown by so quickly. First things first, I am very grateful to have been a part of such a dynamic and talented group of people. I couldn't have asked for a better first job after college. I was mentored by some wonderful people (S/O AAAkash) and I learned so much from everyone around me.

**Learnings from Quadeye:**

1. **Hard work is irreplaceable.** My team consistently pushed me to test my limits and the experience was immensely rewarding. Repeatedly running through ideas in my head and then finally seeing them come to life was peak fulfillment.
2. **Meta-projects are great.** Standardizing procedures and abstracting out common structure across different problems helps you see the bigger picture and draw patterns between different problems. Plus you can now invest resources in solving the common problem well, knowing that this will yield benefit in multiple areas.
3. **Inertia is bad.** I am inherently lazy and avoid re-learning what I can get done with tools I am already familiar with. But with the world changing so rapidly, inertia hurts a lot (even in small spans of ~ 1 year). There is a tradeoff between immediate productivity (output) and learning/adaptability/growth (input) and I used to lean towards the former. Examples for me: smarter terminals (radian), AI coding (cursor), better, faster and cleaner simulation setups.
4. **Perfection is bad.** There have been many instances when I wasted excess time striving for perfection when that extra gain in output was just not worth it. A simple objective (money) helps you understand what's needed and what's not, and the back-prop of undertanding what decisions were good/bad is also easier. I hope to keep this output-centered mindset as I move forward, in contrast to the wow-look-ive-done-something-cool mindset. This is the counter-balance to 3.
5. **Family is everything.** No explanation necessary. Just that being away from home reinforced the importance of family to me.

With all this perspective, I am now moving towards a different stage of life where I re-orient my values and focus on taking the founding steps towards long-term goals.

---

**Quantitative Strategy Internship (2022)**

Before August 2021, I didn’t even know ‘quant’ existed as a field. The whole idea of algorithmic trading was enthralling. I knew I wanted to do a quant internship then, especially after having learned that probability/stats were the cruces of the game. I had never heard of Quadeye before and it didn't look like a well-established company, but since I was so certain about quant, I went ahead and applied for the internship. 

Quadeye turned out to be anything but a random startup. The office was straight-up sexy. There were slightly over 100 employees, and the 50-60 interns had a bay of their own. Two weeks in, I was accustomed to using two monitors, split into six partitions, and working for 10 hours daily. Most of my work revolved around data analysis, with some coding/implementation and some math. In the pre-final week, I had this moment when I finally found the flaw in something we had been trying to create for a few weeks, and it was a glorious feeling when I wrote the code to check my new hypothesis and saw the idea finally working.

---

## Fraazo  
**Tech Internship (2021–2022)**

It was November 2021, and I was a coding geek. Having spent my entire second year developing the <a href="https://www.ee.iitb.ac.in/course/~eesa/"> EESA website</a> and then building <a href="https://not-scotland-yard.herokuapp.com/scotland_yard/"> Scotland Yard</a> in the summer made me confident that I was skilled at web development, and I now wanted to explore how it worked in real life. What better an oppurtunity than working in a rapidly growing startup!

I had to choose between working in back-end or front-end and I chose back-end because I already had a fair idea of how front-end works. Fraazo was the first time I went to an office and it was so much better than I expected it to be. I was comfortable since my very first day and soon, I began writing APIs and designing systems all day. I also developed Fraazo's delivery receipt system, and explored writing optimized database queries to speed jobs up.

We decided to continue the internship into my colllege semester, when I designed and implemented an authorization module. What I learned from the internship is that although I can think around APIs and design systems on paper, there are people with so much experience in the technology (RubyOnRails) that I cant put my ideas into place without their expert guidance.

---

## Indiana University  
**Summer Research Internship (2021)**

We decided to continue the internship into my colllege semester, when I designed and implemented an authorization module. What I learned from the internship is that although I can think around APIs and design systems on paper, there are people with so much experience in the technology (RubyOnRails) that I cant put my ideas into place without their expert guidance.

In the process, I got acquainted with a Python library for bandit algorithm simulations, and I also made significant contributions to it. Apart from learning a lot about writing good, documented code, I also got very familiar with implementing algorithms in a systematic manner, and eventually was able to implement the multi-agent collaborative algorithm proposed by professor Zhang.

Ever since, I have been very interested in Reinforcement Learning, and have thus chosen several electives in college pertaining to the topic.


---

# People I Worked With

## Quadeye (Full-time)
<div class="multicol-2">
- [Aadish Jain](https://in.linkedin.com/in/aadish-jain-7428251b1)
- [Aakash Agarwal / AAAkash](https://in.linkedin.com/in/aakash-agarwal-77980016b) - *Primary mentor*
- [Abhishek Bhatia](https://www.linkedin.com/in/abhishek-bhatia-177248195/)
- [Aditi Goyal](https://in.linkedin.com/in/aditi-goyal-8934641b4)
- [Aditya Badola](https://www.linkedin.com/in/aditya-b-583776205/)
- [Ahaan Malhotra](https://in.linkedin.com/in/ahaan-malhotra)
- [Akshat Gupta](https://in.linkedin.com/in/akshat188)
- [Amit Hooda](https://in.linkedin.com/in/amit-hooda-1ba0172a) - *Partner*
- [Aniket Gupta 1](https://www.linkedin.com/in/aniket-gupta-2867ba246/)
- [Aniket Gupta 2](https://www.linkedin.com/in/aniket-gupta-a2ba141b0/)
- [Aniket Kumar Mishra](https://www.linkedin.com/in/a-k-mishra/)
- [Anindya Sikdar](https://in.linkedin.com/in/anindya-sikdar-071376194)
- [Arpit Gupta](https://www.linkedin.com/in/arpit--gupta/)
- [Ashish Nair](https://www.linkedin.com/in/ashish-r-nair/)
- [Atur Gupta](https://www.linkedin.com/in/atur-gupta/)
- [Bhavuk Bhandula](https://in.linkedin.com/in/bhavukb)
- [Bipplav Tiwari](https://www.linkedin.com/in/bipplav-kumar-tiwari/)
- [Dhruva Dhingra](https://in.linkedin.com/in/dhruva-dhingra)
- [Gaurang Dev](https://in.linkedin.com/in/gaurang-dev-785a51227)
- [Gaurav Gupta](https://in.linkedin.com/in/gaurav-krishan-gupta-a7159421b)
- [Himanshu Sharma](https://in.linkedin.com/in/himanshu-sharma-96a1a592)
- [Hullas Jindal](https://www.linkedin.com/in/hullas-jindal-40457a110/)
- [Lalit Saini](https://in.linkedin.com/in/lalit-saini-eeiitb)
- [Manan Agarwal](https://www.linkedin.com/in/manan-agarwal-cse/)
- [Naman Gupta](https://www.linkedin.com/in/namangup/)
- [Nikhil Agarwal](https://www.linkedin.com/in/nikhil-agarwal27/)
- [Nilay Tiwari](https://www.linkedin.com/in/nilaytiwari/)
- [Paarth Jain](https://in.linkedin.com/in/paarth-jain-950806190)
- [Raunak Jain](https://www.linkedin.com/in/raunak-jain-96a371219/)
- [Rachit Bagga](https://www.linkedin.com/in/rachit-bagga-600611139/)
- [Rajat Bachhawat](https://www.linkedin.com/in/rajatbachhawat/)
- [Sajal Mittal](https://www.linkedin.com/in/sajal-mittal-046396195/)
- [Saksham Singh](https://www.linkedin.com/in/saksham-singh-6b9677208/)
- [Shourya Aggarwal](https://www.linkedin.com/in/shourya-aggarwal-337484163/)
- [Sibasis Nayak](https://in.linkedin.com/in/sibasis-nayak-a05427192)
- [Siddharth Ghetia](https://in.linkedin.com/in/siddharth-ghetia-20290b16a)
- [Sourav Bansal](https://www.linkedin.com/in/sourav-bansal/)
- [Subhrojyoti Chatterjee](https://www.linkedin.com/in/subhrojyoti-chatterjee-294b84194/)
- [Sushant Sondhi](https://www.linkedin.com/in/sushant-sondhi/)
- [Tanay Sharma](https://in.linkedin.com/in/tanay-sharma-abb884189)
- [Vikram Damle](https://in.linkedin.com/in/vikramdamle)
- [Vipul Agarwal](https://www.linkedin.com/in/vipul-agarwal-9492a71a2/)
- [Yatharth Goswami](https://www.linkedin.com/in/yatharth-goswami/)
</div>

---

## Quadeye (Internship)
<div class="multicol-2">
- [Aadish Jain](https://www.linkedin.com/in/aadish-jain-7428251b1/)
- [Adarsh Kumar](https://www.linkedin.com/in/adarsh-kumar-b480b9206/)
- [Aditya Badola](https://www.linkedin.com/in/aditya-b-583776205/)
- [Aniket Gupta](https://www.linkedin.com/in/aniket-gupta-2867ba246/)
- [Anmol Jain](https://www.linkedin.com/in/anmol-abhay-jain-b7375219b/)
- [Anubhav Kalyani](https://www.linkedin.com/in/anubhav-kalyani-b8163a192/)
- [Arsh Gautam](https://www.linkedin.com/in/arshgautam/) - *Primary mentor*
- [Atur Gupta](https://www.linkedin.com/in/atur-gupta/)
- [Devanshu Singla](https://www.linkedin.com/in/dsingla803/)
- [Dhruv Goel](https://www.linkedin.com/in/dhruv-goel-70a4804a/) - *Super mentor*
- [Dhruva Dhingra](https://www.linkedin.com/in/dhruva-dhingra/)
- [Gaurav P](https://www.linkedin.com/in/gaurav-p-b532541a9/)
- [Kanav Gupta](https://www.linkedin.com/in/kanav-gupta-1b6b6b6b6/) - *Super mentor*
- [Krishnam Kapoor](https://www.linkedin.com/in/krishnam-kapoor/) - *Co-mentor*
- [Kritin Sharma](https://www.linkedin.com/in/kritinsharma/)
- [Lakshay Rastogi](https://www.linkedin.com/in/lakshay-rastogi-625563183/)
- [Manan Agarwal](https://www.linkedin.com/in/manan-agarwal-cse/)
- [Nakul Jindal](https://www.linkedin.com/in/nakul-jindal-350a041a5/)
- [Naman Jain](https://www.linkedin.com/in/naman-jain-5a5a80194/)
- [Nikhil Tudaha](https://www.linkedin.com/in/nikhil-tudaha-0a4564194/)
- [Rajat Bachhawat](https://www.linkedin.com/in/rajatbachhawat/)
- [Ridayesh Parab](https://www.linkedin.com/in/ridayesh-parab-8b27341b1/)
- [Rohit Raj](https://www.linkedin.com/in/rohit-raj-67a105156/)
- [Sajal Chhamunya](https://www.linkedin.com/in/sajal-chhamunya/)
- [Sajal Mittal](https://www.linkedin.com/in/sajal-mittal-046396195/)
- [Saksham Jain (co-mentor)](https://www.linkedin.com/in/saksham-jain-081815169/)
- [Sambit Behera](https://www.linkedin.com/in/sambit-b-2a76ba114/)
- [Shravan Nawandar](https://www.linkedin.com/in/shravan-nawandar-7856491ba/)
- [Shrey Patel](https://www.linkedin.com/in/shrey-patel-6567491b1/)
- [Shreyas Dodamani](https://www.linkedin.com/in/shreyasdodamani/)
- [Shubh Jaju](https://www.linkedin.com/in/shubh-jaju-ab7a5b1a5/)
- [Tanmay Bansal (co-mentor)](https://www.linkedin.com/in/tanmay-bansal-1a765115b/)
- [Uttam Sikaria (partner)](https://www.linkedin.com/in/uttam-sikaria-a3213a21/)
- [Yatharth Goswami](https://www.linkedin.com/in/yatharth-goswami/)
</div>

---

## Fraazo
<div class="multicol-2">
- [Dishant Gupta](https://www.linkedin.com/in/dishant-guptaa/)
- [Jay Lahoti](https://www.linkedin.com/in/jay-lahoti-a3556b1aa/)
- [Kunal Chhabra](https://www.linkedin.com/in/kunal-chhabra-6b81b6191/)
- [Mitali Meratwal](https://www.linkedin.com/in/mitali-meratwal-01473b1a6/)
- [Palak Mehta](https://www.linkedin.com/in/palak-mehta-93a934145/)
- [Suraksha Shetty](https://www.linkedin.com/in/suraksha-shetty-4141b5140/)
- [Yash Dave](https://www.linkedin.com/in/yash-dave12345/) - *Mentor*
</div>

---

## Indiana University
- [Chao Tao](https://alanthink.github.io/)
- [Prof. Qin Zhang](https://homes.luddy.indiana.edu/qzhangcs/)
